### ISSUE TITLE
Error with app.use(createIframe);

### ISSUE THREAD

**Issue by arbnorosmani** [A11yWatch/node-iframe#4]
After installing this package and requiring it, when adding **app.use(createIframe);** compiler returns error:

throw new TypeError('app.use() requires a middleware function')

TypeError: app.use() requires a middleware function

my code:
var express = require('express'),
  app = express(),
  port = process.env.PORT || 3000,

const createIframe = require("node-iframe");
app.use(createIframe);

var server = app.listen(port);

**Comment by j-mendez** [comment]
@arbnorosmani thanks for the details. Im trying to reproduce this now. Is that all of code you are trying run?

**Comment by j-mendez** [comment]
> After installing this package and requiring it, when adding **app.use(createIframe);** compiler returns error:
> 
> throw new TypeError('app.use() requires a middleware function')
> 
> TypeError: app.use() requires a middleware function
> 
> my code:
> var express = require('express'),
> app = express(),
> port = process.env.PORT || 3000,
> 
> const createIframe = require("node-iframe");
> app.use(createIframe);
> 
> var server = app.listen(port);

@arbnorosmani what version of node are you using and what is your OS. Check out https://github.com/A11yWatch/a11ywatch/tree/master/iframe-server for example usage.

**Comment by arbnorosmani** [comment]
@j-mendez I am using version 12.16.1 of node and MacOS. Yes, that is the code that I need to run before continuing with other features, but this package is not working as I expected. I am still having the same problem with my project.

**Comment by j-mendez** [comment]
@arbnorosmani I am unable to reproduce the issue. Checkout https://github.com/A11yWatch/node-iframe-example for example usage. Move you'r imports to the top of the file since you have createIframe below the imports. Let me know if this fixes it.

**Comment by arbnorosmani** [comment]
@j-mendez Your example usage seems to work and does the job for me. Thank you for your help and support.
 I only have one more question, as I saw in the example link (https://www.a11ywatch.com/testout) after clicking every link it redirects in the server only URL is changed as a query param like (https://www.a11ywatch.com/testout?websiteUrl=https%3A%2F%2Fwww.drake.com%2Fequipment-panel-overlays) (each href has javascript:void(0)). In the example repository when we click any URL, it redirects us to the website. 
Can you help us on how to implement this feature?

**Comment by j-mendez** [comment]
> @j-mendez Your example usage seems to work and does the job for me. Thank you for your help and support.
> I only have one more question, as I saw in the example link (https://www.a11ywatch.com/testout) after clicking every link it redirects in the server only URL is changed as a query param like (https://www.a11ywatch.com/testout?websiteUrl=https%3A%2F%2Fwww.drake.com%2Fequipment-panel-overlays) (each href has javascript:void(0)). In the example repository when we click any URL, it redirects us to the website.
> Can you help us on how to implement this feature?

Your welcome, and no problem. For the feature your describing you would grab all the possible dom links elements and do something like this after injecting the script into the iframe https://github.com/A11yWatch/a11ywatch/blob/master/web/src/lib/ada/bind.ts

**Comment by j-mendez** [comment]
<img width="947" alt="Screen Shot 2020-09-29 at 3 37 53 PM" src="https://user-images.githubusercontent.com/8095978/94607372-d1d2b200-0269-11eb-9cce-63754b60cc23.png">
@arbnorosmani

**Comment by j-mendez** [comment]
@arbnorosmani if your going to be communicating with the embed a lot use https://developer.mozilla.org/en-US/docs/Web/API/Channel_Messaging_API A11yWatch currently has a slow implementation of manipulating the iframe. https://developer.mozilla.org/en-US/docs/Web/API/Channel_Messaging_API Use the Channel_Messaging API so the main thread is not blocked.
