### ISSUE TITLE
Error on self-signed SSL certificates

### ISSUE THREAD

**Issue by nami-cagla** [A11yWatch/node-iframe#7]
Hi,

I would just like to ask something,
I tried using this library with an https site that I created (it's a self-signed SSL certificate),

and it gives me this error on the server:
> FetchError: request to https://192.168.100.113:8231/login failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:467:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}

and the iFrame shows this:
![image](https://user-images.githubusercontent.com/59039396/111100013-1d63e880-858a-11eb-9090-7f3f2db68b10.png)

Is there anyway you can help me with this one?
Thank you so much!

**Comment by j-mendez** [comment]
@nami-cagla hello, is 192.168.100.113 your local ip address or an ip address from a local docker container? If it is can you try replacing 192.168.100.113 with `localhost` | `0.0.0.0` | `::1` . The last option is ipv6, if none of the above work I would try to see if you can access the url via `http`

**Comment by nami-cagla** [comment]
Hello, I have two urls that I am trying to test (different ports and protocols)
1. http://192.168.100:3000 (this one works with no problem)
2. https://192.168.100:8231 (but this one doesn't work)

and I can't use localhost since it is not in my localhost but in a different server :(

**Comment by j-mendez** [comment]
@nami-cagla I think it has to do with the ssl cert and a missing intermediary. If you having access to the two urls you have to add options to disable strict ssl.  You can use this package to help https://www.npmjs.com/package/node_extra_ca_certs_mozilla_bundle if on node.

**Comment by nami-cagla** [comment]
I see. I'll look into the package that you sent. Thank you so much!! :)

**Comment by j-mendez** [comment]
Your welcome, btw that package needs to be on the server that your
requesting the urls from not the iframe server. Hope this helps.
